### ISSUE TITLE
Finding the highest match between a reference image and a set of images

### ISSUE THREAD

**Issue by Delbina** [lagadic/visp-images#18]
hi,

Does VISP be able to find the highest match image among a set of images with a reference image?

thanks

**Comment by fspindle** [comment]
Not out of the box.

In ViSP there is the [vpKeypoint](https://visp-doc.inria.fr/doxygen/visp-daily/classvpKeyPoint.html) class based on OpenCV that allows to extract keypoints descriptors (SURF, SIFT...) and match them between images ([tutorial](https://visp-doc.inria.fr/doxygen/visp-daily/tutorial-matching.html)).

**Comment by Delbina** [comment]
thanks a lot for your respond,
sorry, what is the difference between this package and https://github.com/lagadic/vision_visp ??
which of them can be used for image matching?

Kind Regards

**Comment by fspindle** [comment]
This package is a data set for [ViSP](https://visp.inria.fr).
[vision_visp](https://github.com/lagadic/vision_visp) is a ROS meta package that contains bridges and tracking nodes
